version: '3'

services:
  xmrstak:
    container_name: xmrstak
    build: .
    tty: true # docker-compose up hangs without
    environment:
      MINER_ID: ${MINER_ID}
      STARTUP_DELAY: ${STARTUP_DELAY}
      STRATUM: ${STRATUM}
      WALLET: ${WALLET}
      PASSWORD: ${PASSWORD}
      CURRENCY: ${CURRENCY}
      THREADS: ${THREADS}
      BLOCKS: ${BLOCKS}
      BFACTOR: ${BFACTOR}
      BSLEEP: ${BSLEEP}
    ports:
      - "8080:8080"
